In [1]:
import geopandas as gpd
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [3]:
df = pd.read_csv('../datasets/strava_edges_2021.csv')

### Basic dataset info

1. `edge_uid` is strava specific ID for a street
2. `osm_reference_id` should be OpenStreetMap way ID - could be a way to match other datasets
3. valuable number: `forward_trip_count`/`reverse_trip_count`  
4. It's possible to download commute data only - leisure trips excluded: Find the quantitative difference
5. maybe export dataset by month/week - possible to aggregate and match with other datasets

In [4]:
display(df.head())
display(f"Shape: {df.shape}")
display("Columns:", df.columns)
display(df.describe())

,edge_uid,activity_type,year,forward_trip_count,reverse_trip_count,forward_people_count,reverse_people_count,forward_commute_trip_count,reverse_commute_trip_count,forward_leisure_trip_count,...,reverse_20_34_people_count,forward_35_54_people_count,reverse_35_54_people_count,forward_55_64_people_count,reverse_55_64_people_count,forward_65_plus_people_count,reverse_65_plus_people_count,forward_average_speed,reverse_average_speed,osm_reference_id
0,160893973,Ride,2021,5,30,5,15,0,0,5,...,0,5,10,0,0,0,0,5.94,3.15,93103358
1,160900085,Ride,2021,5,0,5,0,0,0,5,...,0,5,0,0,0,0,0,1.36,0.00,65201855
2,160901788,Ride,2021,65,65,60,55,5,5,60,...,20,25,20,5,5,0,0,0.56,0.35,33968694
3,160901895,Ride,2021,255,400,85,100,25,20,230,...,20,55,55,0,5,0,0,2.66,4.61,108343596
4,160902450,Ride,2021,75,185,70,130,5,15,70,...,30,35,60,0,10,0,5,2.03,2.60,74064352

'Shape: (193812, 34)'

'Columns:'

Index(['edge_uid', 'activity_type', 'year', 'forward_trip_count',
       'reverse_trip_count', 'forward_people_count', 'reverse_people_count',
       'forward_commute_trip_count', 'reverse_commute_trip_count',
       'forward_leisure_trip_count', 'reverse_leisure_trip_count',
       'forward_morning_trip_count', 'reverse_morning_trip_count',
       'forward_evening_trip_count', 'reverse_evening_trip_count',
       'forward_male_people_count', 'reverse_male_people_count',
       'forward_female_people_count', 'reverse_female_people_count',
       'forward_unspecified_people_count', 'reverse_unspecified_people_count',
       'forward_13_19_people_count', 'reverse_13_19_people_count',
       'forward_20_34_people_count', 'reverse_20_34_people_count',
       'forward_35_54_people_count', 'reverse_35_54_people_count',
       'forward_55_64_people_count', 'reverse_55_64_people_count',
       'forward_65_plus_people_count', 'reverse_65_plus_people_count',
       'forward_average_speed', 'reverse_average_speed', 'osm_reference_id'],
      dtype='object')

,edge_uid,year,forward_trip_count,reverse_trip_count,forward_people_count,reverse_people_count,forward_commute_trip_count,reverse_commute_trip_count,forward_leisure_trip_count,reverse_leisure_trip_count,...,reverse_20_34_people_count,forward_35_54_people_count,reverse_35_54_people_count,forward_55_64_people_count,reverse_55_64_people_count,forward_65_plus_people_count,reverse_65_plus_people_count,forward_average_speed,reverse_average_speed,osm_reference_id
count,1.938120e+05,193812.0,193812.000000,193812.000000,193812.000000,193812.000000,193812.000000,193812.000000,193812.000000,193812.000000,...,193812.000000,193812.000000,193812.000000,193812.000000,193812.00000,193812.000000,193812.000000,193812.000000,193812.000000,1.938120e+05
mean,1.619876e+08,2021.0,328.296674,299.673266,122.016774,114.457619,52.651229,44.795859,275.645445,254.877407,...,40.220265,55.902472,52.790952,4.376638,4.11925,1.105607,1.054579,4.053632,3.816700,2.882771e+08
std,1.366626e+06,0.0,1000.382059,947.005243,269.185387,261.843734,243.399422,216.467870,804.559041,773.482855,...,106.047168,115.831211,112.967226,9.626298,9.36967,2.968917,2.965756,4.211878,5.409011,2.776948e+08
min,1.608657e+08,2021.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,4.019269e+06
25%,1.610366e+08,2021.0,10.000000,10.000000,5.000000,5.000000,0.000000,0.000000,10.000000,10.000000,...,0.000000,5.000000,5.000000,0.000000,0.00000,0.000000,0.000000,2.000000,1.800000,5.201029e+07
50%,1.610995e+08,2021.0,50.000000,40.000000,25.000000,25.000000,5.000000,5.000000,40.000000,35.000000,...,5.000000,15.000000,10.000000,0.000000,0.00000,0.000000,0.000000,3.740000,3.600000,1.776555e+08
75%,1.619703e+08,2021.0,255.000000,220.000000,120.000000,105.000000,20.000000,20.000000,215.000000,190.000000,...,35.000000,55.000000,50.000000,5.000000,5.00000,0.000000,0.000000,5.400000,5.270000,4.308205e+08
max,1.651605e+08,2021.0,27120.000000,27210.000000,4775.000000,4790.000000,7965.000000,8030.000000,21610.000000,21775.000000,...,2175.000000,1810.000000,1810.000000,125.000000,130.00000,45.000000,50.000000,363.990000,1468.950000,1.023971e+09