In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../datasets/strava_daily.csv')

### Basic dataset info

1. `edge_uid` is strava specific ID for a street
2. `osm_reference_id` OpenStreetMap way ID (one OSM way is split into multiple edges in the final dataset)
3. valuable number: `forward_trip_count`/`reverse_trip_count`  
4. It's possible to download commute data only - leisure trips excluded: Find the quantitative difference
5. maybe export dataset by month/week - possible to aggregate and match with other datasets

In [3]:
display(df.head())
display(f"Shape: {df.shape}")
display("Columns:", df.columns)
display(df.describe())

,edge_uid,activity_type,date,total_trip_count,forward_trip_count,reverse_trip_count,forward_people_count,reverse_people_count,forward_commute_trip_count,reverse_commute_trip_count,...,reverse_35_54_people_count,forward_55_64_people_count,reverse_55_64_people_count,forward_65_plus_people_count,reverse_65_plus_people_count,forward_average_speed,reverse_average_speed,osm_reference_id,ride_count,ebike_ride_count
0,175537337,"Ride,EBikeRide",2021-11-09,5,5,0,5,0,0,0,...,0,0,0,0,0,4.91,0.00,4934858,5,0
1,175555034,"Ride,EBikeRide",2021-11-15,5,0,5,0,5,0,0,...,0,0,0,0,0,0.00,8.35,704390536,5,0
2,175555034,"Ride,EBikeRide",2021-11-24,5,0,5,0,5,0,0,...,0,0,0,0,0,0.00,8.83,704390536,5,0
3,175555034,"Ride,EBikeRide",2021-11-11,5,0,5,0,5,0,5,...,0,0,0,0,0,0.00,7.21,704390536,5,0
4,175543106,"Ride,EBikeRide",2021-11-08,5,5,0,5,0,0,0,...,0,0,0,0,0,5.08,0.00,1012860505,5,0

'Shape: (18755, 39)'

'Columns:'

Index(['edge_uid', 'activity_type', 'date', 'total_trip_count',
       'forward_trip_count', 'reverse_trip_count', 'forward_people_count',
       'reverse_people_count', 'forward_commute_trip_count',
       'reverse_commute_trip_count', 'forward_leisure_trip_count',
       'reverse_leisure_trip_count', 'forward_morning_trip_count',
       'reverse_morning_trip_count', 'forward_midday_trip_count',
       'reverse_midday_trip_count', 'forward_evening_trip_count',
       'reverse_evening_trip_count', 'forward_overnight_trip_count',
       'reverse_overnight_trip_count', 'forward_male_people_count',
       'reverse_male_people_count', 'forward_female_people_count',
       'reverse_female_people_count', 'forward_unspecified_people_count',
       'reverse_unspecified_people_count', 'forward_18_34_people_count',
       'reverse_18_34_people_count', 'forward_35_54_people_count',
       'reverse_35_54_people_count', 'forward_55_64_people_count',
       'reverse_55_64_people_count', 'forward_65_plus_people_count',
       'reverse_65_plus_people_count', 'forward_average_speed',
       'reverse_average_speed', 'osm_reference_id', 'ride_count',
       'ebike_ride_count'],
      dtype='object')

,edge_uid,total_trip_count,forward_trip_count,reverse_trip_count,forward_people_count,reverse_people_count,forward_commute_trip_count,reverse_commute_trip_count,forward_leisure_trip_count,reverse_leisure_trip_count,...,reverse_35_54_people_count,forward_55_64_people_count,reverse_55_64_people_count,forward_65_plus_people_count,reverse_65_plus_people_count,forward_average_speed,reverse_average_speed,osm_reference_id,ride_count,ebike_ride_count
count,1.875500e+04,18755.000000,18755.000000,18755.000000,18755.000000,18755.000000,18755.000000,18755.000000,18755.000000,18755.000000,...,18755.000000,18755.000000,18755.000000,18755.0,18755.0,18755.000000,18755.000000,1.875500e+04,18755.000000,18755.000000
mean,1.755464e+08,8.353506,5.096508,3.158091,4.761397,2.890429,1.456145,0.706478,3.721408,2.521461,...,0.527859,0.005332,0.002666,0.0,0.0,4.014524,2.738251,2.997247e+08,8.118102,0.001333
std,8.363597e+03,5.716062,4.758906,3.660548,4.236259,3.107163,2.695711,1.803347,3.573146,3.108881,...,1.552882,0.163195,0.115427,0.0,0.0,5.022920,4.361556,3.211452e+08,5.713716,0.081630
min,1.755350e+08,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,4.020549e+06,0.000000,0.000000
25%,1.755373e+08,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,3.605815e+07,5.000000,0.000000
50%,1.755432e+08,5.000000,5.000000,5.000000,5.000000,5.000000,0.000000,0.000000,5.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,4.510000,0.610000,2.790595e+08,5.000000,0.000000
75%,1.755549e+08,10.000000,5.000000,5.000000,5.000000,5.000000,5.000000,0.000000,5.000000,5.000000,...,0.000000,0.000000,0.000000,0.0,0.0,6.330000,5.370000,3.826781e+08,10.000000,0.000000
max,1.755593e+08,50.000000,35.000000,25.000000,30.000000,15.000000,25.000000,10.000000,30.000000,25.000000,...,10.000000,5.000000,5.000000,0.0,0.0,369.390000,259.280000,1.118056e+09,50.000000,5.000000